-- AlterTable
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "genderPresentation" TEXT;
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "ageRange" TEXT;
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "bodyNotes" TEXT;
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "heightBand" TEXT;
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "constraints" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "inspirationRefs" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "antiRefs" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "formalityRange" TEXT;
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "closetHonesty" TEXT;
ALTER TABLE "StyleProfile" ADD COLUMN IF NOT EXISTS "intakeMode" TEXT NOT NULL DEFAULT 'guided';
